// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CRServerTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cRServer() {
    // Test name: CRServer
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("http://localhost:8000/");
    // 2 | setWindowSize | 814x860 | 
    driver.Manage().Window.Size = new System.Drawing.Size(814, 860);
    // 3 | click | linkText=About us | 
    driver.FindElement(By.LinkText("About us")).Click();
    // 4 | click | linkText=Contact us | 
    driver.FindElement(By.LinkText("Contact us")).Click();
    // 5 | click | linkText=Sign In | 
    driver.FindElement(By.LinkText("Sign In")).Click();
    // 6 | click | linkText=Gallery | 
    driver.FindElement(By.LinkText("Gallery")).Click();
    // 7 | click | id=1 | 
    driver.FindElement(By.Id("1")).Click();
    // 8 | click | css=button | 
    driver.FindElement(By.CssSelector("button")).Click();
    // 9 | click | css=tr:nth-child(3) > td:nth-child(2) > input | 
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input")).Click();
    // 10 | click | css=tr:nth-child(3) > td:nth-child(2) > input | 
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input")).Click();
    // 11 | click | css=tr:nth-child(3) > td:nth-child(2) > input | 
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input")).Click();
    // 12 | click | css=tr:nth-child(3) > td:nth-child(2) > input | 
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input")).Click();
    // 13 | click | css=tr:nth-child(3) > td:nth-child(2) > input | 
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input")).Click();
    // 14 | doubleClick | css=tr:nth-child(3) > td:nth-child(2) > input | 
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    // 15 | click | css=tr:nth-child(3) > td:nth-child(2) > input | 
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input")).Click();
    // 16 | click | css=tr:nth-child(3) > td:nth-child(2) > input | 
    driver.FindElement(By.CssSelector("tr:nth-child(3) > td:nth-child(2) > input")).Click();
    // 17 | click | css=td:nth-child(3) > input | 
    driver.FindElement(By.CssSelector("td:nth-child(3) > input")).Click();
    // 18 | click | css=td:nth-child(3) > input | 
    driver.FindElement(By.CssSelector("td:nth-child(3) > input")).Click();
    // 19 | click | linkText=About us | 
    driver.FindElement(By.LinkText("About us")).Click();
    // 20 | click | css=body | 
    driver.FindElement(By.CssSelector("body")).Click();
    // 21 | click | linkText=Gallery | 
    driver.FindElement(By.LinkText("Gallery")).Click();
    // 22 | click | id=1 | 
    driver.FindElement(By.Id("1")).Click();
    // 23 | click | css=button | 
    driver.FindElement(By.CssSelector("button")).Click();
  }
}
